### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by mansiruhil13** [mansiruhil13/Bobble-AI#1] opened 2024-09-12 04:50 UTC
![Screenshot 2024-09-12 010921](https://github.com/user-attachments/assets/b8a9cd47-6700-4ff3-8232-a01ab50cd752)
![Screenshot 2024-09-12 010955](https://github.com/user-attachments/assets/01683018-4d75-4186-b8ac-c6fe64b70f0b)
![Screenshot 2024-09-12 011016](https://github.com/user-attachments/assets/5329989a-48bc-47d5-b87b-4203decfb8d9)
![Screenshot 2024-09-12 015329](https://github.com/user-attachments/assets/42e3d9c7-ff0b-40a1-80d3-197782ee2ad1)
![Screenshot 2024-09-12 015551](https://github.com/user-attachments/assets/3578d330-2797-4bb2-83dd-cf23ab2b6839)
![Screenshot 2024-09-12 020011](https://github.com/user-attachments/assets/7c77cd05-c512-46a6-b296-554f5a9a6230)
![Screenshot 2024-09-12 092813](https://github.com/user-attachments/assets/6d2663db-d42b-4f34-a780-a22eb394a419)
![Screenshot 2024-09-12 093102](https://github.com/user-attachments/assets/ca008703-2981-4104-bbc9-78e1e9614271)
![Screenshot 2024-09-12 093126](https://github.com/user-attachments/assets/25e576a3-6a21-40cc-9ab4-51a23c240cb5)
![Screenshot 2024-09-12 094532](https://github.com/user-attachments/assets/438cc785-ed34-4e57-9efb-ec1cf8f9bd8b)
![Screenshot 2024-09-12 094551](https://github.com/user-attachments/assets/f1adbbb7-fab0-406e-b483-6287fbfbd700)
![Screenshot 2024-09-12 095153](https://github.com/user-attachments/assets/cb8286fc-3aa6-469f-9816-0adef8079b04)

**Comment by sanaa9012** [comment] 2024-09-21 08:10
Hey, Can you please provide the description of the issue?

**Comment by mansiruhil13** [comment] 2024-09-21 08:14
> Hey, Can you please provide the description of the issue?

When someone is in an emergency or needs medical help, finding the nearest hospital quickly can be crucial.This app helps users find nearby hospitals easily. It shows a list of hospitals and their details like address and rating, so users know where to go for immediate help. And also we track ambulances in real-time on a live map using Google map API.

**Comment by sanaa9012** [comment] 2024-09-21 08:18
Okay, I would like to contribute in it. Can you provide issues, if any?

**Comment by mansiruhil13** [comment] 2024-09-21 08:22
> Okay, I would like to contribute in it. Can you provide issues, if any? 

Repository link - https://github.com/mansiruhil13/Bobble-AI

**Comment by yashksaini-coder** [comment] 2024-09-25 12:42
Hi @mansiruhil13, your issue #1 is opened and it shows the images used in the website, but not telling what is the problem that needs to be fixed. 

Can you tell me a little more about your project, and its intended purpose. So i can understand what it is you want to achieve.
And i would like to contribute on your project to resolve this issue.

@yashksaini-coder

**Comment by mansiruhil13** [comment] 2024-09-25 13:06
> Hi @mansiruhil13, your issue #1 is opened and it shows the images used in the website, but not telling what is the problem that needs to be fixed.
> 
> Can you tell me a little more about your project, and its intended purpose. So i can understand what it is you want to achieve. And i would like to contribute on your project to resolve this issue, so do assign me this issue.
> 
> @yashksaini-coder
my project idea based on: When someone is in an emergency or needs medical help, finding the nearest hospital quickly can be crucial.This app helps users find nearby hospitals easily. It shows a list of hospitals and their details like address and rating, so users know where to go for immediate help. And also we track ambulances in real-time on a live map using Google map API.

**Comment by mansiruhil13** [comment] 2024-09-25 13:07
my project idea based on when someone is in an emergency or needs medical help, finding the nearest hospital quickly can be crucial.This app helps users find nearby hospitals easily. It shows a list of hospitals and their details like address and rating, so users know where to go for immediate help. And also we track ambulances in real-time on a live map using Google map API.

**Comment by yashksaini-coder** [comment] 2024-09-25 13:35
> my project idea based on when someone is in an emergency or needs medical help, finding the nearest hospital quickly can be crucial.This app helps users find nearby hospitals easily. It shows a list of hospitals and their details like address and rating, so users know where to go for immediate help. And also we track ambulances in real-time on a live map using Google map API.

Okh Thank you for providing the reference, so tell me exactly what issues are you facing, that i can contribute to ?

@mansiruhil13

**Comment by mansiruhil13** [comment] 2024-09-25 14:09
in google api keys for location tracking on google map

**Comment by yashksaini-coder** [comment] 2024-09-26 16:30
@mansiruhil13  thanks for assigning the issue, started working on it, can you reopen it so it is visible to all.

**Comment by sanaa9012** [comment] 2024-09-27 16:26
@mansiruhil13 Thanks for assigning the issue. Can you break it down to smaller issues to make the better understanding?

**Comment by yashksaini-coder** [comment] 2024-09-28 08:47
> @mansiruhil13 Thanks for assigning the issue. Can you break it down to smaller issues to make the better understanding?

I would like to contribute on this issue with you. So how about we co-author commits on this issue #1

What do you say @sanaa9012

**Comment by sanaa9012** [comment] 2024-09-28 09:26
@yashksaini-coder Yes yes, I don't have any problem. let's contribute together.

**Comment by sanaa9012** [comment] 2024-09-28 09:34
The thing is I don't excatly get what the issue is.

**Comment by yashksaini-coder** [comment] 2024-09-28 09:35
Great @sanaa9012 You know about co-authoring commits using git cli, we will be doing that. 

I too am having problem in figuring out what seems to be the main problem.
join my discord server to discuss the details here :- here https://discord.gg/gjwS437E

**Comment by yashksaini-coder** [comment] 2024-09-28 15:31
> issue is to enhance live location of ambulance on google map

okh thx @mansiruhil13 that is what we wanted to know. will test the google maps with @sanaa9012

**Comment by mansiruhil13** [comment] 2024-09-28 16:13
> > issue is to enhance live location of ambulance on google map
> 
> okh thx @mansiruhil13 that is what I wanted to know. can you give us the small tasks and divide them and then assigned the issues to us.
> 
> as according to gssoc guidelines. Assigning 2 or more people on a issue is not suggested.

okay, first issue is: i want to enhance live location on google map (fig1) and similarly for live location of driver and ambulance (fig2) 
![Screenshot 2024-09-28 213531](https://github.com/user-attachments/assets/6260e2ea-294f-4b0a-9f23-aefcba1c15c7)
![Screenshot 2024-09-28 213718](https://github.com/user-attachments/assets/94dbbe55-caf6-4718-8894-050dfa2d9ea8)

second issue is: 
in user section, nearby hospitals(open/closed) and after clicking on view on map, map location
![Screenshot 2024-09-12 010955](https://github.com/user-attachments/assets/8c448650-2eb2-4b83-8430-c6fa301eba15)
![Screenshot 2024-09-12 094532](https://github.com/user-attachments/assets/44827ef0-0bac-4456-9b0d-6ffe65439a39)
![Screenshot 2024-09-12 094551](https://github.com/user-attachments/assets/0fe0c760-2dad-4322-b3c3-70ea330c247c) 

3rd issue is:
in hospital section, driver and ambulance status in action.. after clicking on manage and nearby hospitals facilities like bed, oxygen, blood and driver/hospital contact details
![Screenshot 2024-09-12 093126](https://github.com/user-attachments/assets/e432bec8-bc38-4a46-86fb-70a2a2a9d99c)
![Screenshot 2024-09-12 093102](https://github.com/user-attachments/assets/b20735fa-7805-44cd-9496-0c44d54a9f49)

**Comment by yashksaini-coder** [comment] 2024-09-28 17:13
> okay, first issue is: i want to enhance live location on google map (fig1) and similarly for live location of driver and ambulance 
> 
> second issue is: in user section, nearby hospitals(open/closed) and after clicking on view on map, map location 
> 
> 3rd issue is: in hospital section, driver and ambulance status in action.. after clicking on manage and nearby hospitals facilities like bed, oxygen, blood and driver/hospital contact details 

okh @mansiruhil13 I got these tasks, I will be raising issues with the template to fix all these tasks, please assign them.

**Comment by yashksaini-coder** [comment] 2024-10-02 14:45
@mansiruhil13  also close this issue here I divided the tasks & raised 3 prs already regarding to solve this issue and add functionality.

**Closed** 2024-10-02 15:18 UTC
